trigger:
  batch: true
  branches:
    include: 
    - master
variables:
  buildConfiguration: 'Release'
  vmImageName: 'Ubuntu-20.04'
  
stages:

# Build Stage
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: $(vmImageName)
    steps:
    # Build and publish the application library
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    # Publish the app as an artifact
    - publish: $(Build.StagingDirectory)
      artifact: app
      
# Staging release
- stage: Staging
  jobs:
  - job: Release
    pool:
      vmImage: $(vmImageName)
    steps:
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app

    # Release the app
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'AzDO'
        WebAppName: 'csweb08012021'
        package: '$(Pipeline.Workspace)/**/*.zip'
        WebAppKind: WebApp
